### ISSUE TITLE
Change flap.save/load to netCDF?

### ISSUE THREAD

**Issue by sandorzoletnik** [fusion-flap/flap#44]
I was warned that pickle does not have a stable format, it might change from Python version to version. The proposal is to use netCDF or HDF instead.

**Comment by Csega** [comment]
As far as I know, this is not a real problem, since we can specify the format we want to use. I copied this paragraph from the [official Python documentation](https://docs.python.org/3/library/pickle.html#data-stream-format):

> There are currently 5 different protocols which can be used for pickling. The higher the protocol used, the more recent the version of Python needed to read the pickle produced.
> 
> Protocol version 0 is the original “human-readable” protocol and is backwards compatible with earlier versions of Python.
> 
> Protocol version 1 is an old binary format which is also compatible with earlier versions of Python.
> 
> Protocol version 2 was introduced in Python 2.3. It provides much more efficient pickling of new-style classes. Refer to PEP 307 for information about improvements brought by protocol 2.
> 
> Protocol version 3 was added in Python 3.0. It has explicit support for bytes objects and cannot be unpickled by Python 2.x. This is the default protocol, and the recommended protocol when compatibility with other Python 3 versions is required.
> 
> Protocol version 4 was added in Python 3.4. It adds support for very large objects, pickling more kinds of objects, and some data format optimizations. Refer to PEP 3154 for information about improvements brought by protocol 4.

So in my opinion we can use pickle without any problem, we just have to explicitly define the protocol we want to use. Worst-case scenario is, that if (and when) we want to upgrade the protocol we use internally, then we need to convert all our saved data -- which can be automatized. But I don't see right now, why would we want that.

In the case, if we want to use netCDF or HDF, I would suggest, that we use HDF, since as far as I know, it has a wider support. The problem is, that they also do not have a stable format, so in this case, I would suggest netCDF4 or HDF5 (and my vote is on HDF5 from these two). Another difficulty with these formats, that we have to implement all the saving/loading procedures manually for every data structure we want to save/load. With pickle, there are no such problems.

**Comment by sandorzoletnik** [comment]
Good point thank you. So the remaining job is to have an input argument with the pickle version.

**Comment by Csega** [comment]
I would suggest Protocol 3, since it is the default now, and -- according to the documentation -- it is compatible with all Python 3 versions, which is our target version right now. What do you think?

**Comment by sandorzoletnik** [comment]
Done, present in development branch
